var strings = {
	"STR_LOCATION_CHAPAEVSK" : {
		"Language" : "STR_LOCATION_CHAPAEVSK",
		"Original" : "Chapaevsk",
		"English" : "Chapaevsk",
		"French" : "Chapaevsk",
		"Spanish" : "Chapaevsk",
		"Italian" : "Chapaevsk",
		"German" : "Chapaevsk",
		"Russian" : "Чапаевск",
		"Polish" : "",
		"Czech" : "",
		"Hungarian" : "",
		"Japanese" : ""
	},
	"STR_LOCATION_NOVOSELKY" : {
		"Language" : "STR_LOCATION_NOVOSELKY",
		"Original" : "Novoselky",
		"English" : "Novoselky",
		"French" : "Novoselky",
		"Spanish" : "Novoselky",
		"Italian" : "Novoselky",
		"German" : "Novoselky",
		"Russian" : "Новосёлки",
		"Polish" : "Novoselky",
		"Czech" : "Novoselky",
		"Hungarian" : "Novoselky",
		"Japanese" : "Novoselky"
	},
	"STR_LOCATION_DUBKY" : {
		"Language" : "STR_LOCATION_DUBKY",
		"Original" : "Dubky",
		"English" : "Dubky",
		"French" : "Dubky",
		"Spanish" : "Dubky",
		"Italian" : "Dubky",
		"German" : "Dubky",
		"Russian" : "Дубки",
		"Polish" : "Dubky",
		"Czech" : "Dubky",
		"Hungarian" : "Dubky",
		"Japanese" : "Dubky"
	},
	"STR_LOCATION_SHAKHOVKA" : {
		"Language" : "STR_LOCATION_SHAKHOVKA",
		"Original" : "Shakhovka",
		"English" : "Shakhovka",
		"French" : "Shakhovka",
		"Spanish" : "Shakhovka",
		"Italian" : "Shakhovka",
		"German" : "Shakhovka",
		"Russian" : "Шаховка",
		"Polish" : "Szachowka",
		"Czech" : "Šachovka",
		"Hungarian" : "Sakovka",
		"Japanese" : "Shakhovka"
	},
	"STR_LOCATION_DOLINA" : {
		"Language" : "STR_LOCATION_DOLINA",
		"Original" : "Dolina",
		"English" : "Dolina",
		"French" : "Dolina",
		"Spanish" : "Dolina",
		"Italian" : "Dolina",
		"German" : "Dolina",
		"Russian" : "Долина",
		"Polish" : "Dolina",
		"Czech" : "Dolina",
		"Hungarian" : "Dolina",
		"Japanese" : "Dolina"
	},
	"STR_LOCATION_ORLOVETS" : {
		"Language" : "STR_LOCATION_ORLOVETS",
		"Original" : "Orlovets",
		"English" : "Orlovets",
		"French" : "Orlovets",
		"Spanish" : "Orlovets",
		"Italian" : "Orlovets",
		"German" : "Orlovets",
		"Russian" : "Орловец",
		"Polish" : "Orłowiec",
		"Czech" : "Orlovec",
		"Hungarian" : "Orlovec",
		"Japanese" : "Orlovets"
	},
	"STR_LOCATION_BOR" : {
		"Language" : "STR_LOCATION_BOR",
		"Original" : "Bor",
		"English" : "Bor",
		"French" : "Bor",
		"Spanish" : "Bor",
		"Italian" : "Bor",
		"German" : "Bor",
		"Russian" : "Бор",
		"Polish" : "Bor",
		"Czech" : "Bor",
		"Hungarian" : "Bor",
		"Japanese" : "Bor"
	},
	"STR_LOCATION_GORKA" : {
		"Language" : "STR_LOCATION_GORKA",
		"Original" : "Gorka",
		"English" : "Gorka",
		"French" : "Gorka",
		"Spanish" : "Gorka",
		"Italian" : "Gorka",
		"German" : "Gorka",
		"Russian" : "Горка",
		"Polish" : "Gorka",
		"Czech" : "Gorka",
		"Hungarian" : "Gorka",
		"Japanese" : "Gorka"
	},
	"STR_LOCATION_NOVYSOBOR" : {
		"Language" : "STR_LOCATION_NOVYSOBOR",
		"Original" : "Novy Sobor",
		"English" : "Novy Sobor",
		"French" : "Novy Sobor",
		"Spanish" : "Novy Sobor",
		"Italian" : "Novy Sobor",
		"German" : "Novy Sobor",
		"Russian" : "Новый Собор",
		"Polish" : "Nowy Sobor",
		"Czech" : "Nový Sobor",
		"Hungarian" : "Novi Szobor",
		"Japanese" : "Novy Sobor"
	},
	"STR_LOCATION_KABANINO" : {
		"Language" : "STR_LOCATION_KABANINO",
		"Original" : "Kabanino",
		"English" : "Kabanino",
		"French" : "Kabanino",
		"Spanish" : "Kabanino",
		"Italian" : "Kabanino",
		"German" : "Kabanino",
		"Russian" : "Кабанино",
		"Polish" : "Kabanino",
		"Czech" : "Kabanino",
		"Hungarian" : "Kabanino",
		"Japanese" : "Kabanino"
	},
	"STR_LOCATION_MOGILEVKA" : {
		"Language" : "STR_LOCATION_MOGILEVKA",
		"Original" : "Mogilevka",
		"English" : "Mogilevka",
		"French" : "Mogilevka",
		"Spanish" : "Mogilevka",
		"Italian" : "Mogilevka",
		"German" : "Mogilevka",
		"Russian" : "Могилевка",
		"Polish" : "Mogilewka",
		"Czech" : "Mogilevka",
		"Hungarian" : "Mogilevka",
		"Japanese" : "Mogilevka"
	},
	"STR_LOCATION_CHERNOGORSK" : {
		"Language" : "STR_LOCATION_CHERNOGORSK",
		"Original" : "Chernogorsk",
		"English" : "Chernogorsk",
		"French" : "Tchernogorsk",
		"Spanish" : "Chernogorsk",
		"Italian" : "Chernogorsk",
		"German" : "Chernogorsk",
		"Russian" : "Черногорск",
		"Polish" : "Czernogorsk",
		"Czech" : "Černogorsk",
		"Hungarian" : "Csernogorszk",
		"Japanese" : "Chernogorsk"
	},
	"STR_LOCATION_ELEKTROZAVODSK" : {
		"Language" : "STR_LOCATION_ELEKTROZAVODSK",
		"Original" : "Elektrozavodsk",
		"English" : "Elektrozavodsk",
		"French" : "Elektrozavodsk",
		"Spanish" : "Elektrozavodsk",
		"Italian" : "Elektrozavodsk",
		"German" : "Elektrozavodsk",
		"Russian" : "Электрозаводск",
		"Polish" : "Elektrozawodzk",
		"Czech" : "Elektrozavodsk",
		"Hungarian" : "Elektrozavodszk",
		"Japanese" : "Elektrozavodsk"
	},
	"STR_LOCATION_TULGA" : {
		"Language" : "STR_LOCATION_TULGA",
		"Original" : "Tulga",
		"English" : "Tulga",
		"French" : "Tulga",
		"Spanish" : "Tulga",
		"Italian" : "Tulga",
		"German" : "Tulga",
		"Russian" : "Тулга",
		"Polish" : "Tulga",
		"Czech" : "Tulga",
		"Hungarian" : "Tulga",
		"Japanese" : "Tulga"
	},
	"STR_LOCATION_SOLNICHNIY" : {
		"Language" : "STR_LOCATION_SOLNICHNIY",
		"Original" : "Solnichniy",
		"English" : "Solnichniy",
		"French" : "Solnitchniy",
		"Spanish" : "Solnichniy",
		"Italian" : "Solnichniy",
		"German" : "Solnichniy",
		"Russian" : "Солнечный",
		"Polish" : "Sołniczny",
		"Czech" : "Solněčnyj",
		"Hungarian" : "Szolnicsnij",
		"Japanese" : "Solnichniy"
	},
	"STR_LOCATION_BEREZINO" : {
		"Language" : "STR_LOCATION_BEREZINO",
		"Original" : "Berezino",
		"English" : "Berezino",
		"French" : "Berezino",
		"Spanish" : "Berezino",
		"Italian" : "Berezino",
		"German" : "Berezino",
		"Russian" : "Березино",
		"Polish" : "Berezino",
		"Czech" : "Berezino",
		"Hungarian" : "Berezino",
		"Japanese" : "Berezino"
	},
	"STR_LOCATION_STARYSOBOR" : {
		"Language" : "STR_LOCATION_STARYSOBOR",
		"Original" : "Stary Sobor",
		"English" : "Stary Sobor",
		"French" : "Stary Sobor",
		"Spanish" : "Stary Sobor",
		"Italian" : "Stary Sobor",
		"German" : "Stary Sobor",
		"Russian" : "Старый Собор",
		"Polish" : "Stary Sobor",
		"Czech" : "Starý Sobor",
		"Hungarian" : "Sztari Szobor",
		"Japanese" : "Stary Sobor"
	},
	"STR_LOCATION_MSTA" : {
		"Language" : "STR_LOCATION_MSTA",
		"Original" : "Msta",
		"English" : "Msta",
		"French" : "Msta",
		"Spanish" : "Msta",
		"Italian" : "Msta",
		"German" : "Msta",
		"Russian" : "Мста",
		"Polish" : "Msta",
		"Czech" : "Msta",
		"Hungarian" : "Mszta",
		"Japanese" : "Msta"
	},
	"STR_LOCATION_STAROYE" : {
		"Language" : "STR_LOCATION_STAROYE",
		"Original" : "Staroye",
		"English" : "Staroye",
		"French" : "Staroye",
		"Spanish" : "Staroye",
		"Italian" : "Staroye",
		"German" : "Staroye",
		"Russian" : "Старое",
		"Polish" : "Staroje",
		"Czech" : "Staroje",
		"Hungarian" : "Sztaroje",
		"Japanese" : "Staroye"
	},
	"STR_LOCATION_AIRFIELD" : {
		"Language" : "STR_LOCATION_AIRFIELD",
		"Original" : "airfield",
		"English" : "airfield",
		"French" : "aérodrome",
		"Spanish" : "campo aéreo",
		"Italian" : "campo aereo",
		"German" : "Flugfeld",
		"Russian" : "аэродром",
		"Polish" : "lotnisko",
		"Czech" : "letiště",
		"Hungarian" : "repülőtér",
		"Japanese" : "airfield"
	},
	"STR_LOCATION_LOC_OLDFIELDS" : {
		"Language" : "STR_LOCATION_LOC_OLDFIELDS",
		"Original" : "Old Fields",
		"English" : "Old Fields",
		"French" : "Vieux champs",
		"Spanish" : "Campo Viejo",
		"Italian" : "Vecchi campi",
		"German" : "Altes Feld",
		"Russian" : "Старые поля",
		"Polish" : "Stare Pola",
		"Czech" : "Stará Pole",
		"Hungarian" : "Öregrét",
		"Japanese" : "Old Fields"
	},
	"STR_LOCATION_LOC_BLACKFOREST" : {
		"Language" : "STR_LOCATION_LOC_BLACKFOREST",
		"Original" : "Black Forest",
		"English" : "Black Forest",
		"French" : "Forêt noire",
		"Spanish" : "Bosque Negro",
		"Italian" : "Foresta Nera",
		"German" : "Schwarzwald",
		"Russian" : "Черный лес",
		"Polish" : "Czarny Las",
		"Czech" : "Černý Les",
		"Hungarian" : "Fekete-erdő",
		"Japanese" : "Black Forest"
	},
	"STR_LOCATION_LOC_NOVYLUG" : {
		"Language" : "STR_LOCATION_LOC_NOVYLUG",
		"Original" : "Novy Lug",
		"English" : "Novy Lug",
		"French" : "Novy Lug",
		"Spanish" : "Novy Lug",
		"Italian" : "Novy Lug",
		"German" : "Novy Lug",
		"Russian" : "Новый луг",
		"Polish" : "Nowy Ług",
		"Czech" : "Nový Luh",
		"Hungarian" : "Novy Lug",
		"Japanese" : "Novy Lug"
	},
	"STR_LOCATION_LOC_KUMYRNA" : {
		"Language" : "STR_LOCATION_LOC_KUMYRNA",
		"Original" : "Kumyrna",
		"English" : "Kumyrna",
		"French" : "Kumyrna",
		"Spanish" : "Kumyrna",
		"Italian" : "Kumyrna",
		"German" : "Kumyrna",
		"Russian" : "Кумырна",
		"Polish" : "Kumyrna",
		"Czech" : "Kumyrna",
		"Hungarian" : "Kumyrna",
		"Japanese" : "Kumyrna"
	},
	"STR_LOCATION_LOC_PASSORESHKA" : {
		"Language" : "STR_LOCATION_LOC_PASSORESHKA",
		"Original" : "Pass Oreshka",
		"English" : "Pass Oreshka",
		"French" : "Col d'Oreshka",
		"Spanish" : "Paso de Oreshka",
		"Italian" : "Valico di Oreshka",
		"German" : "Pass Oreshka",
		"Russian" : "Перевал Орешка",
		"Polish" : "Przełęcz Oreszka",
		"Czech" : "průsmyk Oreška",
		"Hungarian" : "Oreshka-szoros",
		"Japanese" : "Pass Oreshka"
	},
	"STR_LOCATION_QUARRY" : {
		"Language" : "STR_LOCATION_QUARRY",
		"Original" : "quarry",
		"English" : "quarry",
		"French" : "carrière",
		"Spanish" : "cantera",
		"Italian" : "cava",
		"German" : "Steinbruch",
		"Russian" : "карьер",
		"Polish" : "prom",
		"Czech" : "lom",
		"Hungarian" : "kőfejtő",
		"Japanese" : "quarry"
	},
	"STR_LOCATION_LOC_THREEVALLEYS" : {
		"Language" : "STR_LOCATION_LOC_THREEVALLEYS",
		"Original" : "Three Valleys",
		"English" : "Three Valleys",
		"French" : "Trois vallées",
		"Spanish" : "Tres Valles",
		"Italian" : "Tre valli",
		"German" : "Drei Täler",
		"Russian" : "Три долины",
		"Polish" : "Trzy Doliny",
		"Czech" : "Tři Údolí",
		"Hungarian" : "Háromvölgy",
		"Japanese" : "Three Valleys"
	},
	"STR_LOCATION_LOC_BLUNTROCKS" : {
		"Language" : "STR_LOCATION_LOC_BLUNTROCKS",
		"Original" : "Blunt Rocks",
		"English" : "Blunt Rocks",
		"French" : "Rochers abrupts",
		"Spanish" : "Piedras Romas",
		"Italian" : "Rocce smussate",
		"German" : "Stumpfe Felsen",
		"Russian" : "Тупые скалы",
		"Polish" : "Nagie Skały",
		"Czech" : "Tupé Skály",
		"Hungarian" : "Csonka-szikla",
		"Japanese" : "Blunt Rocks"
	},
	"STR_LOCATION_LUMBERMILL" : {
		"Language" : "STR_LOCATION_LUMBERMILL",
		"Original" : "lumber mill",
		"English" : "lumber mill",
		"French" : "scierie",
		"Spanish" : "aserradero",
		"Italian" : "segheria",
		"German" : "Sägewerk",
		"Russian" : "лесопилка",
		"Polish" : "tartak",
		"Czech" : "pila",
		"Hungarian" : "fűrészmalom",
		"Japanese" : "lumber mill"
	},
	"STR_LOCATION_LOC_OTMEL" : {
		"Language" : "STR_LOCATION_LOC_OTMEL",
		"Original" : "Otmel",
		"English" : "Otmel",
		"French" : "Otmel",
		"Spanish" : "Otmel",
		"Italian" : "Otmel",
		"German" : "Otmel",
		"Russian" : "Отмель",
		"Polish" : "Otmel",
		"Czech" : "Otmel",
		"Hungarian" : "Otmel",
		"Japanese" : "Otmel"
	},
	"STR_LOCATION_LOC_DRAKON" : {
		"Language" : "STR_LOCATION_LOC_DRAKON",
		"Original" : "Drakon",
		"English" : "Drakon",
		"French" : "Drakon",
		"Spanish" : "Drakon",
		"Italian" : "Drakon",
		"German" : "Drakon",
		"Russian" : "Дракон",
		"Polish" : "Drakon",
		"Czech" : "Drakon",
		"Hungarian" : "Drakon",
		"Japanese" : "Drakon"
	},
	"STR_LOCATION_LOC_CAPKRUTOY" : {
		"Language" : "STR_LOCATION_LOC_CAPKRUTOY",
		"Original" : "Krutoy Cap",
		"English" : "Krutoy Cap",
		"French" : "Cap Krutoy",
		"Spanish" : "Cabo Krutoy",
		"Italian" : "Capo Krutoy",
		"German" : "Krutoy Cap",
		"Russian" : "Мыс Крутой",
		"Polish" : "Cypel Krutoj",
		"Czech" : "Strmý mys",
		"Hungarian" : "Krutoy-csúcs",
		"Japanese" : "Krutoy Cap"
	},
	"STR_LOCATION_LOC_ISLANDSKALISTY" : {
		"Language" : "STR_LOCATION_LOC_ISLANDSKALISTY",
		"Original" : "Skalisty Island",
		"English" : "Skalisty Island",
		"French" : "Île de Skalisty",
		"Spanish" : "Isla de Skalisty",
		"Italian" : "Isola Skalisty",
		"German" : "Insel Skalisty",
		"Russian" : "Остров Скалистый",
		"Polish" : "Wyspa Skalista",
		"Czech" : "Skalistý o.",
		"Hungarian" : "Szakiszty-sziget",
		"Japanese" : "Skalisty Island"
	},
	"STR_LOCATION_FACTORY" : {
		"Language" : "STR_LOCATION_FACTORY",
		"Original" : "factory",
		"English" : "factory",
		"French" : "usine",
		"Spanish" : "fábrica",
		"Italian" : "fabbrica",
		"German" : "Fabrik",
		"Russian" : "завод",
		"Polish" : "fabryka",
		"Czech" : "továrna",
		"Hungarian" : "gyár",
		"Japanese" : "factory"
	},
	"STR_LOCATION_LOC_VYSOTA" : {
		"Language" : "STR_LOCATION_LOC_VYSOTA",
		"Original" : "Vysota",
		"English" : "Vysota",
		"French" : "Vysota",
		"Spanish" : "Vysota",
		"Italian" : "Vysota",
		"German" : "Vysota",
		"Russian" : "Высота",
		"Polish" : "Wysota",
		"Czech" : "Vysota",
		"Hungarian" : "Viszota",
		"Japanese" : "Vysota"
	},
	"STR_LOCATION_LOC_KOPYTO" : {
		"Language" : "STR_LOCATION_LOC_KOPYTO",
		"Original" : "Kopyto",
		"English" : "Kopyto",
		"French" : "Kopyto",
		"Spanish" : "Kopyto",
		"Italian" : "Kopyto",
		"German" : "Kopyto",
		"Russian" : "Копыто",
		"Polish" : "Kopyto",
		"Czech" : "Kopyto",
		"Hungarian" : "Kopyto",
		"Japanese" : "Kopyto"
	},
	"STR_LOCATION_LOC_CAPGOLOVA" : {
		"Language" : "STR_LOCATION_LOC_CAPGOLOVA",
		"Original" : "Cap Golova",
		"English" : "Cap Golova",
		"French" : "Cap Golova",
		"Spanish" : "Cabo Golova",
		"Italian" : "Capo Golova",
		"German" : "Cap Golova",
		"Russian" : "Мыс Голова",
		"Polish" : "Cypel Gołowa",
		"Czech" : "mys Hlava",
		"Hungarian" : "Golova-csúcs",
		"Japanese" : "Cap Golova"
	},
	"STR_LOCATION_LOC_PASSGROZOVOY" : {
		"Language" : "STR_LOCATION_LOC_PASSGROZOVOY",
		"Original" : "Grozovoy Pass",
		"English" : "Grozovoy Pass",
		"French" : "Col de Grozovoy",
		"Spanish" : "Paso de Grozovoy",
		"Italian" : "Valico di Grozovoy",
		"German" : "Grozovoy Pass",
		"Russian" : "Перевал Грозовой",
		"Polish" : "Przełęcz Grozowoj",
		"Czech" : "Hromový průsmyk",
		"Hungarian" : "Grozovoy-szoros",
		"Japanese" : "Grozovoy Pass"
	},
	"STR_LOCATION_LOC_PASSSOSNOVY" : {
		"Language" : "STR_LOCATION_LOC_PASSSOSNOVY",
		"Original" : "Pass Sosnovy",
		"English" : "Pass Sosnovy",
		"French" : "Col de Sosnovy",
		"Spanish" : "Paso de Sosnovy",
		"Italian" : "Valico di Sosnovy",
		"German" : "Pass Sosnovy",
		"Russian" : "Перевал Сосновый",
		"Polish" : "Przełęcz Sosnowa",
		"Czech" : "Sosnový průsmyk",
		"Hungarian" : "Szosznovy-szoros",
		"Japanese" : "Pass Sosnovy"
	},
	"STR_LOCATION_LOC_GREENMOUNTAIN" : {
		"Language" : "STR_LOCATION_LOC_GREENMOUNTAIN",
		"Original" : "Green Mountain",
		"English" : "Green Mountain",
		"French" : "Mont vert",
		"Spanish" : "Monte Verde",
		"Italian" : "Montagna Verde",
		"German" : "Grüner Berg",
		"Russian" : "Гора Зеленая",
		"Polish" : "Zielona Góra",
		"Czech" : "Zelená Hora",
		"Hungarian" : "Zöld-hegy",
		"Japanese" : "Green Mountain"
	},
	"STR_LOCATION_AIRSTRIP" : {
		"Language" : "STR_LOCATION_AIRSTRIP",
		"Original" : "airstrip",
		"English" : "airstrip",
		"French" : "piste d'aviation",
		"Spanish" : "pista de aterrizaje",
		"Italian" : "pista d'atterraggio",
		"German" : "Landebahn",
		"Russian" : "ВПП",
		"Polish" : "lądowisko",
		"Czech" : "přistávací plocha",
		"Hungarian" : "kifutópálya",
		"Japanese" : "airstrip"
	},
	"STR_LOCATION_W_DAMTOPOLKA" : {
		"Language" : "STR_LOCATION_W_DAMTOPOLKA",
		"Original" : "Topolka Dam",
		"English" : "Topolka Dam",
		"French" : "Barrage de Topolka",
		"Spanish" : "Dique de Topolka",
		"Italian" : "Diga di Topolka",
		"German" : "Topolka-Damm",
		"Russian" : "Плотина Тополька",
		"Polish" : "Zapora Topołka",
		"Czech" : "přehrada Topolka",
		"Hungarian" : "Topolka-gát",
		"Japanese" : "Topolka Dam"
	},
	"STR_LOCATION_W_OZERKO" : {
		"Language" : "STR_LOCATION_W_OZERKO",
		"Original" : "Ozerko",
		"English" : "Ozerko",
		"French" : "Ozerko",
		"Spanish" : "Ozerko",
		"Italian" : "Ozerko",
		"German" : "Ozerko",
		"Russian" : "Озерко",
		"Polish" : "Ozerko",
		"Czech" : "Jezírko",
		"Hungarian" : "Ozerko",
		"Japanese" : "Ozerko"
	},
	"STR_LOCATION_W_PRUD" : {
		"Language" : "STR_LOCATION_W_PRUD",
		"Original" : "Prud",
		"English" : "Prud",
		"French" : "Prud",
		"Spanish" : "Prud",
		"Italian" : "Prud",
		"German" : "Prud",
		"Russian" : "Пруд",
		"Polish" : "Prud",
		"Czech" : "Prud",
		"Hungarian" : "Prud",
		"Japanese" : "Prud"
	},
	"STR_LOCATION_W_GUBA" : {
		"Language" : "STR_LOCATION_W_GUBA",
		"Original" : "Guba",
		"English" : "Guba",
		"French" : "Guba",
		"Spanish" : "Guba",
		"Italian" : "Guba",
		"German" : "Guba",
		"Russian" : "Губа",
		"Polish" : "Guba",
		"Czech" : "Guba",
		"Hungarian" : "Guba",
		"Japanese" : "Guba"
	},
	"STR_LOCATION_W_RIFY" : {
		"Language" : "STR_LOCATION_W_RIFY",
		"Original" : "Rify",
		"English" : "Rify",
		"French" : "Rify",
		"Spanish" : "Rify",
		"Italian" : "Rify",
		"German" : "Rify",
		"Russian" : "Рифы",
		"Polish" : "Rify",
		"Czech" : "Rify",
		"Hungarian" : "Rify",
		"Japanese" : "Rify"
	},
	"STR_LOCATION_W_LAKEWILLOW" : {
		"Language" : "STR_LOCATION_W_LAKEWILLOW",
		"Original" : "Willow Lake",
		"English" : "Willow Lake",
		"French" : "Lac aux saules",
		"Spanish" : "Lago del Sauce",
		"Italian" : "Lago del Salice",
		"German" : "Weidensee",
		"Russian" : "Озеро Ивовое",
		"Polish" : "Jezioro Wierzba",
		"Czech" : "Vrbové jezero",
		"Hungarian" : "Fűzes-tó",
		"Japanese" : "Willow Lake"
	},
	"STR_LOCATION_W_LAKEBLACK" : {
		"Language" : "STR_LOCATION_W_LAKEBLACK",
		"Original" : "Black Lake",
		"English" : "Black Lake",
		"French" : "Lac noir",
		"Spanish" : "Lago Negro",
		"Italian" : "Lago Nero",
		"German" : "Schwarzer See",
		"Russian" : "Озеро Черное",
		"Polish" : "Jezioro Czarne",
		"Czech" : "Černé jezero",
		"Hungarian" : "Fekete-tó",
		"Japanese" : "Black Lake"
	},
	"STR_LOCATION_W_DAMPOBEDA" : {
		"Language" : "STR_LOCATION_W_DAMPOBEDA",
		"Original" : "Pobeda Dam",
		"English" : "Pobeda Dam",
		"French" : "Barrage de Pobeda",
		"Spanish" : "Dique de Pobeda",
		"Italian" : "Diga di Pobeda",
		"German" : "Pobeda-Damm",
		"Russian" : "Плотина Победа",
		"Polish" : "Zapora Pobeda",
		"Czech" : "přehrada Pobeda",
		"Hungarian" : "Pjobeda-gát",
		"Japanese" : "Pobeda Dam"
	},
	"STR_LOCATION_MYSHKINO" : {
		"Language" : "STR_LOCATION_MYSHKINO",
		"Original" : "Myshkino",
		"English" : "Myshkino",
		"French" : "Myshkino",
		"Spanish" : "Myshkino",
		"Italian" : "Myshkino",
		"German" : "Myshkino",
		"Russian" : "Мышкино",
		"Polish" : "Miszkino",
		"Czech" : "Myškino",
		"Hungarian" : "Miskino",
		"Japanese" : "Myshkino"
	},
	"STR_LOCATION_KAMENKA" : {
		"Language" : "STR_LOCATION_KAMENKA",
		"Original" : "Kamenka",
		"English" : "Kamenka",
		"French" : "Kamenka",
		"Spanish" : "Kamenka",
		"Italian" : "Kamenka",
		"German" : "Kamenka",
		"Russian" : "Каменка",
		"Polish" : "Kamenka",
		"Czech" : "Kamenka",
		"Hungarian" : "Kamenka",
		"Japanese" : "Kamenka"
	},
	"STR_LOCATION_LOC_DICHINA" : {
		"Language" : "STR_LOCATION_LOC_DICHINA",
		"Original" : "Dichina",
		"English" : "Dichina",
		"French" : "Dichina",
		"Spanish" : "Dichina",
		"Italian" : "Dichina",
		"German" : "Dichina",
		"Russian" : "Дичина",
		"Polish" : "Diszina",
		"Czech" : "Dičina",
		"Hungarian" : "Dicsinya",
		"Japanese" : "Dichina"
	},
	"STR_LOCATION_PAVLOVO" : {
		"Language" : "STR_LOCATION_PAVLOVO",
		"Original" : "Pavlovo",
		"English" : "Pavlovo",
		"French" : "Pavlovo",
		"Spanish" : "Pavlovo",
		"Italian" : "Pavlovo",
		"German" : "Pavlovo",
		"Russian" : "Павлово",
		"Polish" : "Pawłowo",
		"Czech" : "Pavlovo",
		"Hungarian" : "Pavlovo",
		"Japanese" : "Pavlovo"
	},
	"STR_LOCATION_LOC_ZUB" : {
		"Language" : "STR_LOCATION_LOC_ZUB",
		"Original" : "Zub",
		"English" : "Zub",
		"French" : "Zub",
		"Spanish" : "Zub",
		"Italian" : "Zub",
		"German" : "Zub",
		"Russian" : "Зуб",
		"Polish" : "Zub",
		"Czech" : "Zub",
		"Hungarian" : "Zub",
		"Japanese" : "Zub"
	},
	"STR_LOCATION_LOC_DEVILSCASTLE" : {
		"Language" : "STR_LOCATION_LOC_DEVILSCASTLE",
		"Original" : "Devil's Castle",
		"English" : "Devil's Castle",
		"French" : "Château du diable",
		"Spanish" : "Castillo del Diablo",
		"Italian" : "Castello del Diavolo",
		"German" : "Teufelsschloss",
		"Russian" : "Чертов замок",
		"Polish" : "Diabelski Zamek",
		"Czech" : "Čertův Hrad",
		"Hungarian" : "Az ördög kastélya",
		"Japanese" : "Devil's Castle"
	},
	"STR_LOCATION_POWERPLANT" : {
		"Language" : "STR_LOCATION_POWERPLANT",
		"Original" : "power plant",
		"English" : "power plant",
		"French" : "centrale",
		"Spanish" : "central eléctrica",
		"Italian" : "centrale elettrica",
		"German" : "Kraftwerk",
		"Russian" : "электростанция",
		"Polish" : "elektrownia",
		"Czech" : "elektrárna",
		"Hungarian" : "erőmű",
		"Japanese" : "power plant"
	},
	"STR_LOCATION_LOC_ROG" : {
		"Language" : "STR_LOCATION_LOC_ROG",
		"Original" : "Rog",
		"English" : "Rog",
		"French" : "Rog",
		"Spanish" : "Rog",
		"Italian" : "Rog",
		"German" : "Rog",
		"Russian" : "Рог",
		"Polish" : "Rog",
		"Czech" : "Rog",
		"Hungarian" : "Rog",
		"Japanese" : "Rog"
	},
	"STR_LOCATION_ROGOVO" : {
		"Language" : "STR_LOCATION_ROGOVO",
		"Original" : "Rogovo",
		"English" : "Rogovo",
		"French" : "Rogovo",
		"Spanish" : "Rogovo",
		"Italian" : "Rogovo",
		"German" : "Rogovo",
		"Russian" : "Рогово",
		"Polish" : "Rogowo",
		"Czech" : "Rogovo",
		"Hungarian" : "Rogovo",
		"Japanese" : "Rogovo"
	},
	"STR_LOCATION_LOC_SKALKA" : {
		"Language" : "STR_LOCATION_LOC_SKALKA",
		"Original" : "Skalka",
		"English" : "Skalka",
		"French" : "Skalka",
		"Spanish" : "Skalka",
		"Italian" : "Skalka",
		"German" : "Skalka",
		"Russian" : "Скалка",
		"Polish" : "Skałka",
		"Czech" : "Skalka",
		"Hungarian" : "Szkalka",
		"Japanese" : "Skalka"
	},
	"STR_LOCATION_PUSTOSHKA" : {
		"Language" : "STR_LOCATION_PUSTOSHKA",
		"Original" : "Pustoshka",
		"English" : "Pustoshka",
		"French" : "Pustoshka",
		"Spanish" : "Pustoshka",
		"Italian" : "Pustoshka",
		"German" : "Pustoschka",
		"Russian" : "Пустошка",
		"Polish" : "Pustoszka",
		"Czech" : "Pustoška",
		"Hungarian" : "Pusztoska",
		"Japanese" : "Pustoshka"
	},
	"STR_LOCATION_POGOREVKA" : {
		"Language" : "STR_LOCATION_POGOREVKA",
		"Original" : "Pogorevka",
		"English" : "Pogorevka",
		"French" : "Pogorevka",
		"Spanish" : "Pogorevka",
		"Italian" : "Pogorevka",
		"German" : "Pogorevka",
		"Russian" : "Погоревка",
		"Polish" : "Pogorewka",
		"Czech" : "Pogorevka",
		"Hungarian" : "Pogorevka",
		"Japanese" : "Pogorevka"
	},
	"STR_LOCATION_POLANA" : {
		"Language" : "STR_LOCATION_POLANA",
		"Original" : "Polana",
		"English" : "Polana",
		"French" : "Polana",
		"Spanish" : "Polana",
		"Italian" : "Polana",
		"German" : "Polana",
		"Russian" : "Поляна",
		"Polish" : "Polana",
		"Czech" : "Polana",
		"Hungarian" : "Polana",
		"Japanese" : "Polana"
	},
	"STR_LOCATION_KOZLOVKA" : {
		"Language" : "STR_LOCATION_KOZLOVKA",
		"Original" : "Kozlovka",
		"English" : "Kozlovka",
		"French" : "Kozlovka",
		"Spanish" : "Kozlovka",
		"Italian" : "Kozlovka",
		"German" : "Kozlovka",
		"Russian" : "Козловка",
		"Polish" : "Kozłowka",
		"Czech" : "Kozlovka",
		"Hungarian" : "Kozlovka",
		"Japanese" : "Kozlovka"
	},
	"STR_LOCATION_KOMAROVO" : {
		"Language" : "STR_LOCATION_KOMAROVO",
		"Original" : "Komarovo",
		"English" : "Komarovo",
		"French" : "Komarovo",
		"Spanish" : "Komarovo",
		"Italian" : "Komarovo",
		"German" : "Komarovo",
		"Russian" : "Комарово",
		"Polish" : "Komarewo",
		"Czech" : "Komarovo",
		"Hungarian" : "Komarovo",
		"Japanese" : "Komarovo"
	},
	"STR_LOCATION_BALOTA" : {
		"Language" : "STR_LOCATION_BALOTA",
		"Original" : "Balota",
		"English" : "Balota",
		"French" : "Balota",
		"Spanish" : "Balota",
		"Italian" : "Balota",
		"German" : "Balota",
		"Russian" : "Балота",
		"Polish" : "Balota",
		"Czech" : "Balota",
		"Hungarian" : "Balota",
		"Japanese" : "Balota"
	},
	"STR_LOCATION_VYBOR" : {
		"Language" : "STR_LOCATION_VYBOR",
		"Original" : "Vybor",
		"English" : "Vybor",
		"French" : "Vybor",
		"Spanish" : "Vybor",
		"Italian" : "Vybor",
		"German" : "Vybor",
		"Russian" : "Выбор",
		"Polish" : "Wibor",
		"Czech" : "Vybor",
		"Hungarian" : "Vibor",
		"Japanese" : "Vybor"
	},
	"STR_LOCATION_DUBROVKA" : {
		"Language" : "STR_LOCATION_DUBROVKA",
		"Original" : "Dubrovka",
		"English" : "Dubrovka",
		"French" : "Dubrovka",
		"Spanish" : "Dubrovka",
		"Italian" : "Dubrovka",
		"German" : "Dubrovka",
		"Russian" : "Дубровка",
		"Polish" : "Dubrowka",
		"Czech" : "Dubrovka",
		"Hungarian" : "Dubrovka",
		"Japanese" : "Dubrovka"
	},
	"STR_LOCATION_KHELM" : {
		"Language" : "STR_LOCATION_KHELM",
		"Original" : "Khelm",
		"English" : "Khelm",
		"French" : "Khelm",
		"Spanish" : "Khelm",
		"Italian" : "Khelm",
		"German" : "Khelm",
		"Russian" : "Хельм",
		"Polish" : "Chelm",
		"Czech" : "Chelm",
		"Hungarian" : "Khelm",
		"Japanese" : "Khelm"
	},
	"STR_LOCATION_OLSHA" : {
		"Language" : "STR_LOCATION_OLSHA",
		"Original" : "Olsha",
		"English" : "Olsha",
		"French" : "Olsha",
		"Spanish" : "Olsha",
		"Italian" : "Olsha",
		"German" : "Olsha",
		"Russian" : "Ольша",
		"Polish" : "Olsza",
		"Czech" : "Olša",
		"Hungarian" : "Olsa",
		"Japanese" : "Olsha"
	},
	"STR_LOCATION_GVOZDNO" : {
		"Language" : "STR_LOCATION_GVOZDNO",
		"Original" : "Gvozdno",
		"English" : "Gvozdno",
		"French" : "Gvozdno",
		"Spanish" : "Gvozdno",
		"Italian" : "Gvozdno",
		"German" : "Gvozdno",
		"Russian" : "Гвоздно",
		"Polish" : "Gwozdno",
		"Czech" : "Gvozdno",
		"Hungarian" : "Gvozdno",
		"Japanese" : "Gvozdno"
	},
	"STR_LOCATION_KRASNOSTAV" : {
		"Language" : "STR_LOCATION_KRASNOSTAV",
		"Original" : "Krasnostav",
		"English" : "Krasnostav",
		"French" : "Krasnostav",
		"Spanish" : "Krasnostav",
		"Italian" : "Krasnostav",
		"German" : "Krasnostav",
		"Russian" : "Красностав",
		"Polish" : "Krasnostaw",
		"Czech" : "Krasnostav",
		"Hungarian" : "Krasznosztav",
		"Japanese" : "Krasnostav"
	},
	"STR_LOCATION_PETROVKA" : {
		"Language" : "STR_LOCATION_PETROVKA",
		"Original" : "Petrovka",
		"English" : "Petrovka",
		"French" : "Petrovka",
		"Spanish" : "Petrovka",
		"Italian" : "Petrovka",
		"German" : "Petrovka",
		"Russian" : "Петровка",
		"Polish" : "Petrowka",
		"Czech" : "Petrovka",
		"Hungarian" : "Petrovka",
		"Japanese" : "Petrovka"
	},
	"STR_LOCATION_GRISHINO" : {
		"Language" : "STR_LOCATION_GRISHINO",
		"Original" : "Grishino",
		"English" : "Grishino",
		"French" : "Grishino",
		"Spanish" : "Grishino",
		"Italian" : "Grishino",
		"German" : "Grishino",
		"Russian" : "Гришино",
		"Polish" : "Griszino",
		"Czech" : "Grišino",
		"Hungarian" : "Grisino",
		"Japanese" : "Grishino"
	},
	"STR_LOCATION_NADEZHDINO" : {
		"Language" : "STR_LOCATION_NADEZHDINO",
		"Original" : "Nadezhdino",
		"English" : "Nadezhdino",
		"French" : "Nadezhdino",
		"Spanish" : "Nadezhdino",
		"Italian" : "Nadezhdino",
		"German" : "Nadezhdino",
		"Russian" : "Надеждино",
		"Polish" : "Nadieżdino",
		"Czech" : "Naděždino",
		"Hungarian" : "Nadezsdijnyo",
		"Japanese" : "Nadezhdino"
	},
	"STR_LOCATION_MT_PIKKOZLOVA" : {
		"Language" : "STR_LOCATION_MT_PIKKOZLOVA",
		"Original" : "Pik Kozlova",
		"English" : "Pik Kozlova",
		"French" : "Pik Kozlova",
		"Spanish" : "Pik Kozlova",
		"Italian" : "Pik Kozlova",
		"German" : "Pik Kozlova",
		"Russian" : "Пик Козлова",
		"Polish" : "Pik Kozłowa",
		"Czech" : "Pik Kozlova",
		"Hungarian" : "Pik Kozljova",
		"Japanese" : "Pik Kozlova"
	},
	"STR_LOCATION_MT_ALTAR" : {
		"Language" : "STR_LOCATION_MT_ALTAR",
		"Original" : "Altar",
		"English" : "Altar",
		"French" : "Autel",
		"Spanish" : "Altar",
		"Italian" : "Altar",
		"German" : "Altar",
		"Russian" : "Алтарь",
		"Polish" : "Altar",
		"Czech" : "Altar",
		"Hungarian" : "Altar",
		"Japanese" : "Altar"
	},
	"STR_LOCATION_MT_RIDGEPOSTOY" : {
		"Language" : "STR_LOCATION_MT_RIDGEPOSTOY",
		"Original" : "Pustoy Khrebet",
		"English" : "Pustoy Khrebet",
		"French" : "Pustoy Khrebet",
		"Spanish" : "Pustoy Khrebet",
		"Italian" : "Pustoy Khrebet",
		"German" : "Pustoy Khrebet",
		"Russian" : "Пустой хребет",
		"Polish" : "Pustoj Khrebet",
		"Czech" : "Pustý Hřbet",
		"Hungarian" : "Pusztoj Khrebet",
		"Japanese" : "Pustoy Khrebet"
	},
	"STR_LOCATION_GUGLOVO" : {
		"Language" : "STR_LOCATION_GUGLOVO",
		"Original" : "Guglovo",
		"English" : "Guglovo",
		"French" : "Guglovo",
		"Spanish" : "Guglovo",
		"Italian" : "Guglovo",
		"German" : "Guglovo",
		"Russian" : "Гуглово",
		"Polish" : "Gugłowo",
		"Czech" : "Guglovo",
		"Hungarian" : "Guglovo",
		"Japanese" : "Guglovo"
	},
	"STR_LOCATION_KAMYSHOVO" : {
		"Language" : "STR_LOCATION_KAMYSHOVO",
		"Original" : "Kamyshovo",
		"English" : "Kamyshovo",
		"French" : "Kamyshovo",
		"Spanish" : "Kamyshovo",
		"Italian" : "Kamyshovo",
		"German" : "Kamyshovo",
		"Russian" : "Камышово",
		"Polish" : "Kamiszowo",
		"Czech" : "Kamyševo",
		"Hungarian" : "Kamisovo",
		"Japanese" : "Kamyshovo"
	},
	"STR_LOCATION_PUSTA" : {
		"Language" : "STR_LOCATION_PUSTA",
		"Original" : "Pusta",
		"English" : "Pusta",
		"French" : "Pusta",
		"Spanish" : "Pusta",
		"Italian" : "Pusta",
		"German" : "Pusta",
		"Russian" : "Пуста",
		"Polish" : "Pusta",
		"Czech" : "Pusta",
		"Hungarian" : "Pusta",
		"Japanese" : "Pusta"
	},
	"STR_LOCATION_ZELENOGORSK" : {
		"Language" : "STR_LOCATION_ZELENOGORSK",
		"Original" : "Zelenogorsk",
		"English" : "Zelenogorsk",
		"French" : "Zelenogorsk",
		"Spanish" : "Zelenogorsk",
		"Italian" : "Zelenogorsk",
		"German" : "Zelenogorsk",
		"Russian" : "Зеленогорск",
		"Polish" : "Zielenogorsk",
		"Czech" : "Zelenogorsk",
		"Hungarian" : "Zelenogorszk",
		"Japanese" : "Zelenogorsk"
	},
	"STR_LOCATION_W_BAYMUTNAYA" : {
		"Language" : "STR_LOCATION_W_BAYMUTNAYA",
		"Original" : "Bay Mutnaya",
		"English" : "Bay Mutnaya",
		"French" : "Baie Mutnaya",
		"Spanish" : "Bahía de Mutnaya",
		"Italian" : "Baia Mutnaya",
		"German" : "Mutnaya Bucht",
		"Russian" : "Бухта Мутная",
		"Polish" : "Zatoka Spokojna",
		"Czech" : "Kalná zátoka",
		"Hungarian" : "Mutnyaja-öböl",
		"Japanese" : "Bay Mutnaya"
	},
	"STR_LOCATION_W_BAYTIKHAYA" : {
		"Language" : "STR_LOCATION_W_BAYTIKHAYA",
		"Original" : "Bay Tikhaya",
		"English" : "Bay Tikhaya",
		"French" : "Baie Tikhaya",
		"Spanish" : "Bahía de Tikhaya",
		"Italian" : "Baia Tikhaya",
		"German" : "Tikhaya Bucht",
		"Russian" : "Бухта Тихая",
		"Polish" : "Zatoka Cicha",
		"Czech" : "Tichá zátoka",
		"Hungarian" : "Tikhaja-öböl",
		"Japanese" : "Bay Tikhaya"
	},
	"STR_LOCATION_MT_OLSHA" : {
		"Language" : "STR_LOCATION_MT_OLSHA",
		"Original" : "Olsha",
		"English" : "Olsha",
		"French" : "Olsha",
		"Spanish" : "Olsha",
		"Italian" : "Olsha",
		"German" : "Olsha",
		"Russian" : "Ольша",
		"Polish" : "Olsza",
		"Czech" : "Olša",
		"Hungarian" : "Olsha",
		"Japanese" : "Olsha"
	},
	"STR_LOCATION_MT_OSTRY" : {
		"Language" : "STR_LOCATION_MT_OSTRY",
		"Original" : "Ostry",
		"English" : "Ostry",
		"French" : "Ostry",
		"Spanish" : "Ostry",
		"Italian" : "Ostry",
		"German" : "Ostry",
		"Russian" : "Острый",
		"Polish" : "Ostry",
		"Czech" : "Ostrý",
		"Hungarian" : "Osztrij",
		"Japanese" : "Ostry"
	},
	"STR_LOCATION_W_BAYNIZHNAYA" : {
		"Language" : "STR_LOCATION_W_BAYNIZHNAYA",
		"Original" : "Bay Nizhnaya",
		"English" : "Bay Nizhnaya",
		"French" : "Baie Nizhnaya",
		"Spanish" : "Bahía de Nizhnaya",
		"Italian" : "Baia Nizhnaya",
		"German" : "Nizhnaya Bucht",
		"Russian" : "Бухта Нижняя",
		"Polish" : "Zatoka Niska",
		"Czech" : "Dolní zátoka",
		"Hungarian" : "Nyizsnyaja-öböl",
		"Japanese" : "Bay Nizhnaya"
	},
	"STR_LOCATION_W_SKALISTYPROLIV" : {
		"Language" : "STR_LOCATION_W_SKALISTYPROLIV",
		"Original" : "Skalisty Proliv",
		"English" : "Skalisty Proliv",
		"French" : "Skalisty Proliv",
		"Spanish" : "Skalisty Proliv",
		"Italian" : "Skalisty Proliv",
		"German" : "Skalisty Proliv",
		"Russian" : "Пролив Скалистый",
		"Polish" : "Skalisty Przesmyk",
		"Czech" : "Skalistý průliv",
		"Hungarian" : "Szkaliszty Proliv",
		"Japanese" : "Skalisty Proliv"
	},
	"STR_LOCATION_W_BAYZELENAYA" : {
		"Language" : "STR_LOCATION_W_BAYZELENAYA",
		"Original" : "Bay Zelenaya",
		"English" : "Bay Zelenaya",
		"French" : "Baie Zelenaya",
		"Spanish" : "Bahía de Zelenaya",
		"Italian" : "Baia Zelenaya",
		"German" : "Zelenaya Bucht",
		"Russian" : "Бухта Зеленая",
		"Polish" : "Zatoka Zielona",
		"Czech" : "Zelená zátoka",
		"Hungarian" : "Zelenyaja-öböl",
		"Japanese" : "Bay Zelenaya"
	},
	"STR_LOCATION_W_BAYCHYORNAYA" : {
		"Language" : "STR_LOCATION_W_BAYCHYORNAYA",
		"Original" : "Chyornaya Bay",
		"English" : "Chyornaya Bay",
		"French" : "Baie Tchyornaya",
		"Spanish" : "Bahía de Chyornaya",
		"Italian" : "Baia Chyornaya",
		"German" : "Chyornaya Bucht",
		"Russian" : "Бухта Черная",
		"Polish" : "Zatoka Czarna",
		"Czech" : "Černá zátoka",
		"Hungarian" : "Csjornyaja-öböl",
		"Japanese" : "Chyornaya Bay"
	},
	"STR_LOCATION_MT_BARANCHIK" : {
		"Language" : "STR_LOCATION_MT_BARANCHIK",
		"Original" : "Baranchik",
		"English" : "Baranchik",
		"French" : "Baranchik",
		"Spanish" : "Baranchik",
		"Italian" : "Baranchik",
		"German" : "Baranchik",
		"Russian" : "Баранчик",
		"Polish" : "Baranczik",
		"Czech" : "Barančik",
		"Hungarian" : "Barancsik",
		"Japanese" : "Baranchik"
	},
	"STR_LOCATION_MT_DOBRYY" : {
		"Language" : "STR_LOCATION_MT_DOBRYY",
		"Original" : "Dobryy",
		"English" : "Dobryy",
		"French" : "Dobryy",
		"Spanish" : "Dobryy",
		"Italian" : "Dobryy",
		"German" : "Dobryy",
		"Russian" : "Добрый",
		"Polish" : "Dobry",
		"Czech" : "Dobrý",
		"Hungarian" : "Dobryy",
		"Japanese" : "Dobryy"
	},
	"STR_LOCATION_MT_VYSOKYKAMEN" : {
		"Language" : "STR_LOCATION_MT_VYSOKYKAMEN",
		"Original" : "Vysoky Kamen",
		"English" : "Vysoky Kamen",
		"French" : "Vysoky Kamen",
		"Spanish" : "Vysoky Kamen",
		"Italian" : "Vysoky Kamen",
		"German" : "Vysoky Kamen",
		"Russian" : "Высокий камень",
		"Polish" : "Wysoki Kamień",
		"Czech" : "Vysoký Kámen",
		"Hungarian" : "Viszoky Kamen",
		"Japanese" : "Vysoky Kamen"
	},
	"STR_LOCATION_MT_RIDGELESNOY" : {
		"Language" : "STR_LOCATION_MT_RIDGELESNOY",
		"Original" : "Lesnoy Khrebet",
		"English" : "Lesnoy Khrebet",
		"French" : "Lesnoy Khrebet",
		"Spanish" : "Lesnoy Khrebet",
		"Italian" : "Lesnoy Khrebet",
		"German" : "Lesnoy Khrebet",
		"Russian" : "Лесной хребет",
		"Polish" : "Lesnoj Khrebet",
		"Czech" : "Lesní Hřbet",
		"Hungarian" : "Lesznyoj Khrebet",
		"Japanese" : "Lesnoy Khrebet"
	},
	"STR_LOCATION_MT_BLACKMT" : {
		"Language" : "STR_LOCATION_MT_BLACKMT",
		"Original" : "Black Mountain",
		"English" : "Black Mountain",
		"French" : "Mont noir",
		"Spanish" : "Monte Negro",
		"Italian" : "Montagna Nera",
		"German" : "Schwarzer Berg",
		"Russian" : "Гора Черная",
		"Polish" : "Czarna Góra",
		"Czech" : "Černá hora",
		"Hungarian" : "Fekete-hegy",
		"Japanese" : "Black Mountain"
	},
	"STR_LOCATION_MT_KLEN" : {
		"Language" : "STR_LOCATION_MT_KLEN",
		"Original" : "Klen",
		"English" : "Klen",
		"French" : "Klen",
		"Spanish" : "Klen",
		"Italian" : "Klen",
		"German" : "Klen",
		"Russian" : "Клен",
		"Polish" : "Klen",
		"Czech" : "Klen",
		"Hungarian" : "Klen",
		"Japanese" : "Klen"
	},
	"STR_LOCATION_MT_DUBINA" : {
		"Language" : "STR_LOCATION_MT_DUBINA",
		"Original" : "Dubina",
		"English" : "Dubina",
		"French" : "Dubina",
		"Spanish" : "Dubina",
		"Italian" : "Dubina",
		"German" : "Dubina",
		"Russian" : "Дубина",
		"Polish" : "Dubina",
		"Czech" : "Dubina",
		"Hungarian" : "Dubina",
		"Japanese" : "Dubina"
	},
	"STR_LOCATION_MT_MALINOVKA" : {
		"Language" : "STR_LOCATION_MT_MALINOVKA",
		"Original" : "Malinovka",
		"English" : "Malinovka",
		"French" : "Malinovka",
		"Spanish" : "Malinovka",
		"Italian" : "Malinovka",
		"German" : "Malinovka",
		"Russian" : "Малиновка",
		"Polish" : "Malinowka",
		"Czech" : "Malinovka",
		"Hungarian" : "Malinovka",
		"Japanese" : "Malinovka"
	},
	"STR_LOCATION_MT_VERESNIK" : {
		"Language" : "STR_LOCATION_MT_VERESNIK",
		"Original" : "Veresnik",
		"English" : "Veresnik",
		"French" : "Veresnik",
		"Spanish" : "Veresnik",
		"Italian" : "Veresnik",
		"German" : "Veresnik",
		"Russian" : "Вересник",
		"Polish" : "Weresnik",
		"Czech" : "Veresnik",
		"Hungarian" : "Verezsnyik",
		"Japanese" : "Veresnik"
	},
	"STR_LOCATION_MT_KURGAN" : {
		"Language" : "STR_LOCATION_MT_KURGAN",
		"Original" : "Kurgan",
		"English" : "Kurgan",
		"French" : "Kurgan",
		"Spanish" : "Kurgan",
		"Italian" : "Kurgan",
		"German" : "Kurgan",
		"Russian" : "Курган",
		"Polish" : "Kurgan",
		"Czech" : "Kurgan",
		"Hungarian" : "Kurgan",
		"Japanese" : "Kurgan"
	},
	"STR_LOCATION_MT_MISTYPEAK" : {
		"Language" : "STR_LOCATION_MT_MISTYPEAK",
		"Original" : "Misty Peak",
		"English" : "Misty Peak",
		"French" : "Pic brumeux",
		"Spanish" : "Monte Nebuloso",
		"Italian" : "Misty Peak",
		"German" : "Nebelspitze",
		"Russian" : "Пик Туманный",
		"Polish" : "Wzgórze Mgliste",
		"Czech" : "Mlžný",
		"Hungarian" : "Ködös-csúcs",
		"Japanese" : "Misty Peak"
	},
	"STR_LOCATION_MT_BASHNYA" : {
		"Language" : "STR_LOCATION_MT_BASHNYA",
		"Original" : "Bashnya",
		"English" : "Bashnya",
		"French" : "Bashnya",
		"Spanish" : "Bashnya",
		"Italian" : "Bashnya",
		"German" : "Bashnya",
		"Russian" : "Башня",
		"Polish" : "Basznia",
		"Czech" : "Bašňa",
		"Hungarian" : "Basnyja",
		"Japanese" : "Bashnya"
	},
	"STR_LOCATION_MT_LITTLEHILL" : {
		"Language" : "STR_LOCATION_MT_LITTLEHILL",
		"Original" : "Little Hill",
		"English" : "Little Hill",
		"French" : "Petite colline",
		"Spanish" : "Colina",
		"Italian" : "Collinetta",
		"German" : "Kleiner Hügel",
		"Russian" : "Маленький холм",
		"Polish" : "Wzgórze Małe",
		"Czech" : "Malý Vrch",
		"Hungarian" : "Kis-hegy",
		"Japanese" : "Little Hill"
	},
	"STR_LOCATION_MT_POPIVAN" : {
		"Language" : "STR_LOCATION_MT_POPIVAN",
		"Original" : "Pop Ivan",
		"English" : "Pop Ivan",
		"French" : "Pop Ivan",
		"Spanish" : "Pop Ivan",
		"Italian" : "Pop Ivan",
		"German" : "Pop Ivan",
		"Russian" : "Поп Иван",
		"Polish" : "Pop Iwan",
		"Czech" : "Pop Ivan",
		"Hungarian" : "Pop Ivan",
		"Japanese" : "Pop Ivan"
	},
	"STR_LOCATION_MT_KUSTRYK" : {
		"Language" : "STR_LOCATION_MT_KUSTRYK",
		"Original" : "Kustryk",
		"English" : "Kustryk",
		"French" : "Kustryk",
		"Spanish" : "Kustryk",
		"Italian" : "Kustryk",
		"German" : "Kustryk",
		"Russian" : "Кустрик",
		"Polish" : "Kustryk",
		"Czech" : "Kustryk",
		"Hungarian" : "Kusztrik",
		"Japanese" : "Kustryk"
	},
	"STR_LOCATION_MT_WINDYMT" : {
		"Language" : "STR_LOCATION_MT_WINDYMT",
		"Original" : "Windy Mountain",
		"English" : "Windy Mountain",
		"French" : "Mont venteux",
		"Spanish" : "Monte Ventoso",
		"Italian" : "Montagna Ventosa",
		"German" : "Windberg",
		"Russian" : "Гора Ветряная",
		"Polish" : "Góra Wiatrów",
		"Czech" : "Větrná",
		"Hungarian" : "Szeles-hegység",
		"Japanese" : "Windy Mountain"
	},
	"STR_LOCATION_PRIGORODKI" : {
		"Language" : "STR_LOCATION_PRIGORODKI",
		"Original" : "Prigorodki",
		"English" : "Prigorodki",
		"French" : "Prigorodki",
		"Spanish" : "Prigorodki",
		"Italian" : "Prigorodki",
		"German" : "Prigorodki",
		"Russian" : "Пригородки",
		"Polish" : "Prigorodki",
		"Czech" : "Prigorodky",
		"Hungarian" : "Prigorodki",
		"Japanese" : "Prigorodki"
	},
	"STR_LOCATION_DROZHINO" : {
		"Language" : "STR_LOCATION_DROZHINO",
		"Original" : "Drozhino",
		"English" : "Drozhino",
		"French" : "Drozhino",
		"Spanish" : "Drozhino",
		"Italian" : "Drozhino",
		"German" : "Drozhino",
		"Russian" : "Дрожино",
		"Polish" : "Drożino",
		"Czech" : "Drožino",
		"Hungarian" : "Drozino",
		"Japanese" : "Drozhino"
	},
	"STR_LOCATION_LOPATINO" : {
		"Language" : "STR_LOCATION_LOPATINO",
		"Original" : "Lopatino",
		"English" : "Lopatino",
		"French" : "Lopatino",
		"Spanish" : "Lopatino",
		"Italian" : "Lopatino",
		"German" : "Lopatino",
		"Russian" : "Лопатино",
		"Polish" : "Lopatino",
		"Czech" : "Lopatino",
		"Hungarian" : "Lopatino",
		"Japanese" : "Lopatino"
	},
	"STR_LOCATION_VYSHNOE" : {
		"Language" : "STR_LOCATION_VYSHNOE",
		"Original" : "Vyshnoye",
		"English" : "Vyshnoye",
		"French" : "Vishnoye",
		"Spanish" : "Vyshnoe",
		"Italian" : "Vyshnoye",
		"German" : "Vyshnoye",
		"Russian" : "Вышное",
		"Polish" : "Wisznoje",
		"Czech" : "Vyšnoje",
		"Hungarian" : "Visnoje",
		"Japanese" : "Vyshnoye"
	},
	"STR_LOCATION_PULKOVO" : {
		"Language" : "STR_LOCATION_PULKOVO",
		"Original" : "Pulkovo",
		"English" : "Pulkovo",
		"French" : "Pulkovo",
		"Spanish" : "Pulkovo",
		"Italian" : "Pulkovo",
		"German" : "Pulkowo",
		"Russian" : "Пулково",
		"Polish" : "Pulkowo",
		"Czech" : "Pulkovo",
		"Hungarian" : "Pulkovo",
		"Japanese" : "Pulkovo"
	},
	"STR_LOCATION_MT_LYSINA" : {
		"Language" : "STR_LOCATION_MT_LYSINA",
		"Original" : "Lysina",
		"English" : "Lysina",
		"French" : "Lysina",
		"Spanish" : "Lysina",
		"Italian" : "Lysina",
		"German" : "Lysina",
		"Russian" : "Лысина",
		"Polish" : "Łysina",
		"Czech" : "Lysina",
		"Hungarian" : "Liszina",
		"Japanese" : "Lysina"
	},
	"STR_LOCATION_SOSNOVKA" : {
		"Language" : "STR_LOCATION_SOSNOVKA",
		"Original" : "Sosnovka",
		"English" : "Sosnovka",
		"French" : "Sosnovka",
		"Spanish" : "Sosnovka",
		"Italian" : "Sosnovka",
		"German" : "Sosnovka",
		"Russian" : "Сосновка",
		"Polish" : "Sosnowka",
		"Czech" : "Sosnovka",
		"Hungarian" : "Szosnovka",
		"Japanese" : "Sosnovka"
	},
	"STR_LOCATION_NIZHNOYE" : {
		"Language" : "STR_LOCATION_NIZHNOYE",
		"Original" : "Nizhnoye",
		"English" : "Nizhnoye",
		"French" : "Nizhnoye",
		"Spanish" : "Nizhnoye",
		"Italian" : "Nizhnoye",
		"German" : "Nizhnoye",
		"Russian" : "Нижнее",
		"Polish" : "Niżnoje",
		"Czech" : "Nižnoje",
		"Hungarian" : "Nyizsnyoje",
		"Japanese" : "Nizhnoye"
	}
}; 